Add Global Username List
enwikipedia-acc/waca pull request #678
Opened 2021-02-28 21:26 UTC by methecooldude

Resolves #671

2021-02-28 21:34 UTC, methecooldude commented
Additionally resolves #624

2021-03-01 14:22 UTC, stwalkerster requested changes
Thanks! 

The code here looks fine, I just have one stylistic nitpick - the existing code uses four spaces for indentation, not tabs. Would you mind changing the tabs to spaces for consistency?

2021-03-01 14:23 UTC, methecooldude commented
> Thanks!
> 
> The code here looks fine, I just have one stylistic nitpick - the existing code uses four spaces for indentation, not tabs. Would you mind changing the tabs to spaces for consistency?

You can blame my Notepad++ for that... I'll fix it up

2021-03-01 14:30 UTC, stwalkerster submitted a review, later dismissed

2021-03-01 14:36 UTC, stwalkerster approved these changes

2021-03-01 20:54 UTC, merged