Add skipAutoWelcome to resolve #877
enwikipedia-acc/waca pull request #878
Opened 2023-10-28 00:57 UTC by methecooldude

I believe these will resolve #877 per comments from stw

The third, checkReserveProtect, doesn't need adjusting as it doesn't use showConfirmation

2023-10-28 12:31 UTC, stwalkerster requested changes

2023-10-28 12:31 UTC, stwalkerster commented on includes/Pages/RequestAction/PageCloseRequest.php
> +        $this->assign('skipAutoWelcome', webRequest::postBoolean('skipAutoWelcome') ? 'true' : 'false');
```suggestion
        $this->assign('skipAutoWelcome', WebRequest::postBoolean('skipAutoWelcome') ? 'true' : 'false');
```

2023-10-28 12:36 UTC, methecooldude commented on includes/Pages/RequestAction/PageCloseRequest.php
> +        $this->assign('skipAutoWelcome', webRequest::postBoolean('skipAutoWelcome') ? 'true' : 'false');
Oh, Derp...

2023-11-03 00:33 UTC, stwalkerster approved these changes
lgtm

2023-11-03 00:34 UTC, merged